server:
  port: 10003
spring:
  profiles:
    active: dev
  application:
    name: gateway-server

# hystrix 信号量隔离，3秒后自动超时
hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE
#          thread:
#            timeoutInMilliseconds: 3000
  shareSecurityContext: true

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 打印网关日志信息
logging:
  level:
    org.springframework.cloud.gateway: info

---
spring:
  profiles: dev
  redis:
    password: 123456
    host: 47.107.144.40
    lettuce:
      pool:
        max-idle: 10
        min-idle: 0
        max-active: 20
        max-wait: -1
    timeout: 3000
# 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/


---
spring:
  profiles: prod
  redis:
    password: 123456
    host: 47.107.144.40
    lettuce:
      pool:
        max-idle: 10
        min-idle: 0
        max-active: 20
        max-wait: -1
    timeout: 3000
# 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/
